apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pools.elasticsearch.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.kubectlReplicasAnnotation
    description: nodes status for pool
    format: byte
    name: ready
    type: string
  group: elasticsearch.k8s.io
  names:
    kind: Pool
    plural: pools
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            nodeSelector:
              description: Persistence  Persistence             `json:"persistence,omitempty"`
              type: object
            replicas:
              format: int32
              type: integer
            resources:
              type: object
            roles:
              items:
                enum:
                - master
                - data
                - ingest
                type: string
              type: array
            storageClass:
              type: string
          required:
          - replicas
          - name
          type: object
        status:
          properties:
            kubectlReplicasAnnotation:
              description: 'keeps string repr of pools for kubectl formatting. TODO(owen):
                figure out how to format instead of adding a field that needs to be
                updated'
              type: string
            statefulSets:
              description: ReadyReplicas maps statefulset names to the number of alive
                replicas. This can include statefulsets that aren't in the spec (i.e.
                if a cluster updates and drops a node pool)
              type: object
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
