apiVersion: elasticsearch.k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: mycluster
spec:
  # Add fields here
  nodePools:
    - name: master-next
      roles:
        - master
        - data
      replicas: 2
      storageClass: "standard"
      resources:
        requests:
          memory: "512Mi"
          cpu: "300m"
          # memory: "1Gi"
          # cpu: "500m"
    # - name: data
    #   roles:
    #     - data
    #   replicas: 2
    #   storageClass: "standard"
    #   resources:
    #     requests:
    #       memory: "64Mi"
    #       cpu: "50m"
    # - name: ingest
    #   roles:
    #     - ingest
    #   replicas: 0
    #   storageClass: "standard"
    #   resources:
    #     requests:
    #       memory: "64Mi"
    #       cpu: "50m"
