apiVersion: elasticsearch.k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  # Add fields here
  nodePools:
    - name: master
      replicas: 2
    - name: data
      replicas: 2
    - name: ingest
      replicas: 2
