apiVersion: elasticsearch.k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  # Add fields here
  nodePools:
    - name: master
      roles:
        - master
      replicas: 1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
    - name: data
      roles:
        - data
        - ingest
      replicas: 2
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
    - name: ingest
      replicas: 0
